/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fact */

#ifndef _Included_fact
#define _Included_fact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fact
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fact_factorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
